//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelCrud.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personel
    {
        public int Id { get; set; }

        [Display(Name ="Departman Adý")]
        [Required(ErrorMessage ="Departman Adý seçiniz!")]
        public Nullable<int> DepartmanId { get; set; }

        [Required]
        public string Ad { get; set; }

        [Required]
        public string Soyad { get; set; }

        [Display(Name = "Maaþ")]
       // [Required(ErrorMessage = "Maaþ alaný boþ olamaz!")]

        [Range(1399,8000,ErrorMessage ="Maaþ 1400 ile 8000 arasýnda olmalýdýr!")]
        public Nullable<short> Maas { get; set; }

        [Display(Name = "Doðum Tarihi")]
        [Required(ErrorMessage ="Doðum Tarihi alaný boþ olamaz!")]
        public Nullable<System.DateTime> DogumGunu { get; set; }

        [Required]
        public Nullable<bool> Cinsiyet { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
